spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: appusr
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # <--- เปลี่ยนตรงนี้เป็น update
    show-sql: true
    properties:
      hibernate:
        format_sql: true